config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users

  root to: 'restaurants#index'

  devise_scope :user do
    get 'users/sign_out', to: 'devise/sessions#destroy'
  end

  get "dishes/search", to: "dishes#search"
  resource :users
  resources :restaurants do
    resources :dishes
  end
  resources :categories
  resources :carts
  resources :cart_items
  resources :orders, only: [:index, :create, :show, :destroy]
end

app/models/dish.rb
class Dish < ApplicationRecord
  has_one_attached :image, dependent: :destroy
  has_many :order_items
  has_many :orders, through: :order_items
  has_many :cart_items
  has_many :carts, through: :cart_items
  belongs_to :restaurant
  belongs_to :category

  validates :name, uniqueness: {scope: :restaurant_id}, presence: true
  validates :price, presence: true, numericality: { greater_than: 0 }

  def self.ransackable_attributes(auth_object = nil)
    ["category_id", "created_at", "id", "name", "price", "restaurant_id", "updated_at"]
  end

  def self.ransackable_associations(auth_object = nil)
    ["cart_items", "carts", "category", "image_attachment", "image_blob", "order_items", "orders", "restaurant"]
  end

end

app/controllers/dishes_controller.rb
class DishesController < ApplicationController

  before_action :owner_has_right_to, only: [:create,:update,:destroy]
  before_action :choose_restaurant, only: [:index]

  def index
    if current_user.type == "Owner"
      @dishes = selected_restaurant.dishes.all
      if @dishes.nil?
        render notice:"Restaurants have no dishes added"
      else
        render :index, notice: "Your Restaurant Dishes"
      end
    else
      @dishes = Dish.all
      respond_to do |format|
        format.json { render json: Dish.all }
        format.html {  }
      end
    end
    # @restaurants
    # @dishes = Restaurant.find_by_id(params[:restaurant_id]).dishes.all
    # @dishes = selected_restaurant.dishes.all if current_user.type == "Owner"
    # if @dishes.nil?
    #     render :index, notice:"Restaurants have no dishes added"
    # else
    #     render :index, notice: "Your choosen Restaurant Dishes"
    # end
  end

  def new
    @restaurant = selected_restaurant
    @dish = @restaurant.dishes.new
  end

  def create
    @dish = selected_restaurant.dishes.new(set_params)
    if @dish.save
      redirect_to restaurant_dishes_path(@restaurant), notice: "User's dish Created"
    else
      # byebug
      render :new, notice: "User's dish doesn'ts Created"
    end
  end

  def show
    @dish =  if current_user.type == "Owner"
              selected_dish
            else
              Dish.find_by_id(params[:id])
            end
    render :show, notice:"Here is your choosen dish"
  end

  def edit
    @dish = selected_dish
  end

  def update
    @dish = selected_dish
    return render :show, notice:"Updated dish" if @dish.update(set_params)
    render :show, notice: "Dish doesn't update"
  end

  def destroy
    @dish = selected_dish
    return render :index, notice: "dish deleted succesfully" if @dish.destroy
    render :show, alert: "dish doesn't deleted succesfully"
  end

  def search
    if params[:name]
      render json: Dish.where(name:params[:name])
    elsif params[:category_id]
      render json: Dish.where(category_id:params[:category_id])
    end
  end

#----------------------------PRIVATE METHOD-------------------------------------

  private
    def set_params
      # byebug
      params.require(:dish).permit(:name,:price,:category_id,:image)
    end

    def selected_restaurant
      @restaurant = Restaurant.where(user_id: current_user.id).find_by_id(params[:restaurant_id])
    end

    def selected_dish
      @restaurant = selected_restaurant
      @dish = @restaurant.dishes.find_by_id(params[:id])
      if @dish.nil?
        render :index, notice: "No such dish added in our restaurants"\
      else
        return @dish
      end
    end

end

app/views/dishes/edit.html.erb
<h2>Add Dish to your's <%=@restaurant.name%> </h2>

  <%= form_with(model: [@restaurant, @dish] , url: restaurant_dish_path(@restaurant, @dish), method: :put, local: true, data: { turbo: false }) do |f| %>

    <div class="form-group">
      <%= f.label :name, 'Dish Name' %><br>
      <%= f.text_field :name, class: 'form-control' %>
      <% @dish.errors.full_messages_for(:name).each do |message| %>
        <li><%= message %></li>
      <% end %>
      <br>
    </div>

    <div class="form-group">
      <%= f.label :price, 'Price' %><br>
      <%= f.text_field :price, class: 'form-control' %>
      <% @dish.errors.full_messages_for(:price).each do |message| %>
        <li><%= message %></li>
      <% end %>
      <br>
    </div>

    <div class="form-group">
      <%= f.label :category_id, 'Category' %><br>
      <%= f.text_field :category_id, class: 'form-control' %>
      <% @dish.errors.full_messages_for(:category_id).each do |message| %>
        <li><%= message %></li>
      <% end %>
      <br>
    </div>

    <div class="row">
      <div class="small-3 columns actions ">
        <%= f.submit "Done", class: "btn btn-primary" %>
      </div>
    </div>

  <% end %>


<%= link_to "Back", :back, class: 'btn btn-secondary' %>

app/views/dishes/index.html.erb
<%# <% if current_user.type == 'Owner' %>
  <h1><%= @restaurant.name %></h1>

  <p>Status : <%= @restaurant.status %></p>
  <p>Location : <%= @restaurant.location %></p>

  <br>
<%# <% end %>


<h1>Dish List</h1>

<table>

  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Category</th>
    </tr>
  </thead>

  <tbody>
    <% @dishes.each do |dish| %>
      <tr>

        <td><%= link_to dish.name, restaurant_dish_path(@restaurant, dish) %></td>
        <td><%= link_to dish.price, restaurant_dish_path(@restaurant, dish) %></td>
        <td><%= link_to dish.category.name, restaurant_dish_path(@restaurant, dish) %></td>
      </tr>
    <% end %>
  </tbody>

</table>

<br>

<%= link_to "Back", restaurants_path, class: 'btn btn-secondary' %>

<% if current_user.type == 'Owner' %>
  <%= link_to "Add Dishes", new_restaurant_dish_path(@restaurant) %>
<% end %>

app/views/dishes/new.html.erb
<h2>Add Dish to your's <%=@restaurant.name%> </h2>

  <%= form_with(model: [@restaurant, @dish] , url: restaurant_dishes_path(@restaurant, @dish), method: :post, local: true, data: { turbo: false }) do |f| %>

    <div class="form-group">
      <%= f.label :name, 'Dish Name' %><br>
      <%= f.text_field :name, class: 'form-control' %>
      <% @dish.errors.full_messages_for(:name).each do |message| %>
        <li><%= message %></li>
      <% end %>
      <br>
    </div>

    <div class="form-group">
      <%= f.label :price, 'Price' %><br>
      <%= f.text_field :price, class: 'form-control' %>
      <% @dish.errors.full_messages_for(:price).each do |message| %>
        <li><%= message %></li>
      <% end %>
      <br>
    </div>

    <div class="form-group">
      <%= f.label :category_id, 'Category' %><br>
      <%= f.text_field :category_id, class: 'form-control' %>
      <% @dish.errors.full_messages_for(:category_id).each do |message| %>
        <li><%= message %></li>
      <% end %>
      <br>
    </div>

    <div class="form-group">
      <%= f.label :image, 'Image' %><br>
      <%= f.file_field :image, class: 'form-control' %>
      <br>
    </div>

    <div class="row">
      <div class="small-3 columns actions ">
        <%= f.submit "Done", class: "btn btn-primary" %>
      </div>
    </div>

  <% end %>


<%= link_to "Back", restaurant_dishes_path, class: 'btn btn-secondary' %>

app/views/dishes/show.html.erb
<h1><%= @dish.name %></h1>

<table>
  <tbody>
    <% if @dish.image.present? %>
      <%= image_tag(@dish.image, width: 100) %><br>
    <% end %>
    <tr>Price : <%= @dish.price %></tr><br>
    <tr>Location : <%= @dish.restaurant.location %></tr><br>
    <tr> Restaurant Name : <%= @dish.restaurant.name %></tr><br>
  </tbody>
</table>

<%= link_to "Back", restaurant_dishes_path, class: 'btn btn-secondary' %>

<% if current_user.type == 'Owner' %>
  <%= link_to "edit", edit_restaurant_dish_path(@restaurant, @dish), class: 'btn btn-secondary' %>
  <%= link_to "Destroy", restaurant_dish_path(@restaurant, @dish) , data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
<% end %>

<% if current_user.type == 'Customer' %>
  <div>
    <a href="cart_items/new", method: :post><img src="https://as1.ftcdn.net/v2/jpg/01/97/42/26/1000_F_197422696_i5ryVwvLmxfpBj70IVG7dTGsSmtbLCAu.jpg" alt="Profile", width="100"></a>
  </div>
<% end %>